[package]
edition = "2024"
name = "mq-mcp"
version = "0.1.0"

[dependencies]
miette = {version = "7.6.0", features = ["fancy"]}
mq-hir = {git = "https://github.com/harehare/mq.git", package = "mq-hir"}
mq-lang = {git = "https://github.com/harehare/mq.git", package = "mq-lang"}
mq-markdown = {git = "https://github.com/harehare/mq.git", package = "mq-markdown"}
rmcp = {version = "0.9.0", features = ["server"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread", "io-std"]}

[dev-dependencies]
mq-test = {git = "https://github.com/harehare/mq.git", package = "mq-test"}
rstest = "0.26.1"

[lib]
name = "mq_mcp"
path = "src/lib.rs"
