[package]
authors = ["Takahiro Sato <harehare1110@gmail.com>"]
categories = ["command-line-utilities", "text-processing"]
description = "Markdown Query - MCP server implementation"
edition = "2024"
homepage = "https://mqlang.org/"
keywords = ["markdown", "jq", "query", "mcp"]
license = "MIT"
name = "mq-mcp"
readme = "README.md"
repository = "https://github.com/harehare/mq"
version = "0.1.4"

[dependencies]
miette = {version = "7.6.0", features = ["fancy"]}
mq-hir = "0.5.9"
mq-lang = "0.5.9"
mq-markdown = "0.5.9"
rmcp = {version = "0.9.0", features = ["server"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread", "io-std"]}
tracing = "0.1.43"
tracing-subscriber = {version = "0.3.22", features = ["env-filter"]}

[dev-dependencies]
rstest = "0.26.1"

[lib]
name = "mq_mcp"
path = "src/lib.rs"

